config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show]
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'react-items', to: 'portfolios#react'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p><%= @copyright %></p>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Banjoko Azeez</h3>
    <nav class="nav nav-masthead justify-content-center">
      <%= link_to 'Home', root_path, class: 'nav-link' %>
      <%= link_to 'About', about_path, class: 'nav-link' %>
      <%= link_to 'Contact', contact_path, class: 'nav-link' %>
      <%= link_to 'Blog', blogs_path, class: 'nav-link' %>
      <%= link_to 'Portfolio', portfolios_path, class: 'nav-link' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</header>

app/views/shared/_nav.html.erb
    <div class="<%= location %>">
      <div><%= link_to 'Home', root_path %></div>
      <div><%= link_to 'About', about_path %></div>
      <div><%= link_to 'Contact', contact_path %></div>
      <div><%= link_to 'Blog', blogs_path %></div>
      <div><%= link_to 'Portfolio', portfolios_path %></div>
    </div>